return {
  "williamboman/mason.nvim",
  -- opts will be merged with the parent spec
  opts = {
    ensure_installed = {
      -- "autopep8",
      -- "bash-language-server",
      -- "black",
      -- "clang-format",
      -- "clangd",
      -- "glint",
      -- "goimports",
      -- "golangci-lint",
      -- "golangci-lint-langserver",
      -- "golines",
      -- "gopls",
      -- "gotests",
      -- "isort",
      -- "jedi-language-server",
      -- "json-lsp",
      -- "lua-language-server",
      -- "prettier",
      -- "pyright",
      -- "python-lsp-server",
      -- "rust-analyzer",
      -- "shellcheck",
      -- "shfmt",
      -- "stylua",
      "autoflake",
      "autopep8",
      "awk-language-server",
      "basedpyright",
      "bash-language-server",
      "black",
      "clang-format",
      "clangd",
      "codelldb",
      "css-lsp",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "emmet-language-server",
      "emmet-ls",
      "eslint-lsp",
      "glint",
      "gofumpt",
      "goimports",
      "golangci-lint",
      "golangci-lint-langserver",
      "golines",
      "gopls",
      "gotests",
      "hadolint",
      "hyprls",
      "isort",
      "jedi-language-server",
      "json-lsp",
      "lua-language-server",
      "markdown-toc",
      "markdownlint",
      "markdownlint-cli2",
      "marksman",
      "prettier",
      "pyright",
      "python-lsp-server",
      "ruff",
      "ruff-lsp",
      "rust-analyzer",
      "shellcheck",
      "shfmt",
      "stylua",
      "taplo",
      "typescript-language-server",
      "vtsls",
      "yaml-language-server",
    },
  },
}
