return {
  "williamboman/mason.nvim",
  -- opts will be merged with the parent spec
  opts = {
    ensure_installed = {
      "autopep8",
      "bash-language-server",
      "black",
      "clang-format",
      "clangd",
      "glint",
      "goimports",
      "golangci-lint",
      "golangci-lint-langserver",
      "golines",
      "gopls",
      "gotests",
      "isort",
      "jedi-language-server",
      "json-lsp",
      "lua-language-server",
      "prettier",
      "pyright",
      "python-lsp-server",
      "rust-analyzer",
      "shellcheck",
      "shfmt",
      "stylua",
    },
  },
}
